// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	find_by_id_user "github.com/FelipeAragao/must-have/internal/usecase/user/find_by_id"
	mock "github.com/stretchr/testify/mock"
)

// FindByIDUseCaseInterface is an autogenerated mock type for the FindByIDUseCaseInterface type
type FindByIDUseCaseInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *FindByIDUseCaseInterface) Execute(input *find_by_id_user.UserInputDTO) (*find_by_id_user.UserOutputDTO, error) {
	ret := _m.Called(input)

	var r0 *find_by_id_user.UserOutputDTO
	if rf, ok := ret.Get(0).(func(*find_by_id_user.UserInputDTO) *find_by_id_user.UserOutputDTO); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*find_by_id_user.UserOutputDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*find_by_id_user.UserInputDTO) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFindByIDUseCaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewFindByIDUseCaseInterface creates a new instance of FindByIDUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFindByIDUseCaseInterface(t mockConstructorTestingTNewFindByIDUseCaseInterface) *FindByIDUseCaseInterface {
	mock := &FindByIDUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
