// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	update_user "github.com/FelipeAragao/must-have/internal/usecase/user/update_user"
	mock "github.com/stretchr/testify/mock"
)

// UpdateUserUseCaseInterface is an autogenerated mock type for the UpdateUserUseCaseInterface type
type UpdateUserUseCaseInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *UpdateUserUseCaseInterface) Execute(input *update_user.UserInputDTO) (*update_user.UserOutputDTO, error) {
	ret := _m.Called(input)

	var r0 *update_user.UserOutputDTO
	if rf, ok := ret.Get(0).(func(*update_user.UserInputDTO) *update_user.UserOutputDTO); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*update_user.UserOutputDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*update_user.UserInputDTO) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUpdateUserUseCaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateUserUseCaseInterface creates a new instance of UpdateUserUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateUserUseCaseInterface(t mockConstructorTestingTNewUpdateUserUseCaseInterface) *UpdateUserUseCaseInterface {
	mock := &UpdateUserUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
