// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"github.com/FelipeAragao/must-have/internal/domain/gateway"
	"github.com/FelipeAragao/must-have/internal/infra/database"
	"github.com/FelipeAragao/must-have/internal/usecase/user/user_verifier"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserVerifier(db *sql.DB) *user_verifier.UserVerifier {
	userRepository := database.NewUserRepository(db)
	userVerifier := user_verifier.NewUserVerifier(userRepository)
	return userVerifier
}

// wire.go:

var setRepositoryDependency = wire.NewSet(database.NewUserRepository, wire.Bind(new(gateway.UserGateway), new(*database.UserRepository)))
