### Create new User

#URI sugerida: /api/v{n}/users
#Public: Não
#Tipo: POST
#Request: { "name": STRING, "email": STRING, "login": STRING; "password": STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING, “zip_code” : INT } }
#Return Success: { "user" : OBJECT }
#Return Fail: { "error" : "" }

POST {{host}}/users
Content-Type: application/json

{
  "name":"John Doe",
  "email":"john.doe@vibbra.com.br",
  "login":"john.doe",
  "password": "abc123639",
  "location": {
    "lat": -23.5506507,
    "lng": -46.6333824,
    "address": "Rua Vergueiro, 3185",
    "city": "São Paulo",
    "state": "SP",
    "zip_code": 65000000
  }
}


> {% client.global.set("user_id", response.body.json.user.id); %}

### Authenticate Users
POST {{host}}/authenticate
Content-Type: application/x-www-form-urlencoded
User-Agent: Fiddler
Host: localhost:3000

grant_type=password&username=john.doe&password=abc123639


> {%
    client.global.set("token", response.body.access_token)
    client.global.set("user_id", response.body.properties.user_id)
%}

### Update User
#URI sugerida: /api/v{n}/users/{ID}
#Public: Não
#Tipo: PUT
#Request: { "name": STRING, "email": STRING, "login": STRING; "password": STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING, “zip_code” : INT } }
#Return Success: { "user" : OBJECT }
#Return Fail: { "error" : STRING }

PUT {{host}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Silva",
  "email": "john.silva@vibbra.com.br",
  "login": "john.doe",
  "location": {
    "lat": -23.5506507,
    "lng": -46.6333824,
    "address": "Rua Vergueiro, 3185",
    "city": "São Paulo",
    "state": "SP",
    "zip_code": 65000000
  }
}

### Find User
#URI sugerida: /api/v{n}/users/{ID}
#Public: NÃO
#Tipo: GET
#Return Success: { "user" : OBJECT }
#Return Fail: { "error" : STRING }


GET {{host}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}


### change password
PUT {{host}}/users/{{user_id}}/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "abc123639",
  "new_password": "123639abc"
}


