### Create Deal
#URI sugerida: /api/v{n}/deals
#Public: NÃO
#Tipo: POST
#Request: { “type” : ENUM (1 – Venda, 2 – Troca, 3 – Desejo), “value” : DOUBLE, “description” : STRING, “trade_for” : STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING , “zip_code” : INT }, “urgency” : { “type” : ENUM (1 – Baixa, 2 – Média, 3 – Alta, 4 – Data), “limit_date” : DATE}, “photos“ : [ LIST OF IMAGES ]}
#Return Success: { “deal": OBJECT }
#Return Fail: { "error" : STRING }

POST {{host}}/deals
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": 2,
  "value": 1776.45,
  "description": "Aliquip mollit aute aliqua ut. In nisi non est voluptate anim consequat veniam quis. Nostrud ullamco esse nostrud dolor elit eu esse nulla incididunt magna. Laboris eu quis laborum nostrud esse et consectetur exercitation. Duis minim irure proident sint occaecat cillum officia deserunt.\r\n",
  "trade_for": "",
  "location": {
    "lat": -67.868968,
    "lng": -12.943469,
    "address": "460 Hamilton Avenue, Oberlin, Michigan, 2608",
    "city": "Eastvale",
    "state": "Indiana",
    "zip_code": 171947677
  },
  "urgency": {
    "type": 1,
    "limit_date": "2021-05-31"
  },
  "photos": [
    "http://placehold.it/32x32"
  ]
}

> {% client.global.set("deal_id", response.body.json.deal.id); %}

### Update Deal
#URI sugerida: /api/v{n}/deals/{ID}
#Public: NÃO
#Tipo: PUT
#Request: { “type” : ENUM (1 – Venda, 2 – Troca, 3 – Desejo), “value” : DOUBLE, “description” : STRING, “trade_for” : STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING , “zip_code” : INT }, “urgency” : { “type” : ENUM (1 – Baixa, 2 – Média, 3 – Alta, 4 – Data), “limit_date” : DATE}, “photos“ : [ LIST OF IMAGES ]}
#Return Success: { “deal": OBJECT }
#Return Fail: { "error" : STRING }

PUT {{host}}/deals/{{deal_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": 2,
  "value": 1776.45,
  "description": "Aliquip mollit aute aliqua ut. In nisi non est voluptate anim consequat veniam quis. Nostrud ullamco esse nostrud dolor elit eu esse nulla incididunt magna. Laboris eu quis laborum nostrud esse et consectetur exercitation. Duis minim irure proident sint occaecat cillum officia deserunt.\r\n",
  "trade_for": "",
  "location": {
    "lat": -67.868968,
    "lng": -12.943469,
    "address": "460 Hamilton Avenue, Oberlin, Michigan, 2608",
    "city": "Eastvale",
    "state": "Indiana",
    "zip_code": 171947677
  },
  "urgency": {
    "type": 1,
    "limit_date": "2021-05-31"
  },
  "photos": [
    "http://placehold.it/32x32"
  ]
}

### Find Deal
#URI sugerida: /api/v{n}/deals/{ID}
#Public: NÃO
#Tipo: GET
#Return Success: { “deal": OBJECT }
#Return Fail: { "error" : STRING }

GET {{host}}/deals/{{deal_id}}
Authorization: Bearer {{token}}
Content-Type: application/json



