basePath: /api/v1
definitions:
  change_password.UserInputDTO:
    properties:
      id:
        type: string
      password:
        type: string
      passwordNew:
        type: string
    type: object
  create_user.UserInputDTO:
    properties:
      email:
        type: string
      location:
        properties:
          address:
            type: string
          city:
            type: string
          lat:
            type: number
          lng:
            type: number
          state:
            type: string
          zip_code:
            type: integer
        type: object
      login:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  entity.Location:
    properties:
      address:
        maxLength: 100
        minLength: 3
        type: string
      city:
        maxLength: 100
        minLength: 3
        type: string
      lat:
        type: number
      lng:
        type: number
      state:
        maxLength: 2
        minLength: 2
        type: string
      zip_code:
        maximum: 99999999
        minimum: 10000000
        type: integer
    required:
    - address
    - city
    - lat
    - lng
    - state
    - zip_code
    type: object
  entity.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/entity.Location'
      login:
        maxLength: 50
        minLength: 3
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      updated_at:
        type: string
    required:
    - email
    - location
    - login
    - name
    type: object
  handlers.Error:
    properties:
      message:
        type: string
    type: object
  update_user.UserInputDTO:
    properties:
      email:
        type: string
      id:
        type: string
      location:
        properties:
          address:
            type: string
          city:
            type: string
          lat:
            type: number
          lng:
            type: number
          state:
            type: string
          zip_code:
            type: integer
        type: object
      login:
        type: string
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: felipe.thiago10@gmail.com
    name: Felipe Aragão
  description: Must Have API with auhtentication
  termsOfService: http://swagger.io/terms/
  title: Must Have API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/create_user.UserInputDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Create user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user
      parameters:
      - description: user ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      security:
      - ApiKeyAuth: []
      summary: Get a user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update a user
      parameters:
      - description: user ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/update_user.UserInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      security:
      - ApiKeyAuth: []
      summary: Update a user
      tags:
      - users
  /users/{id}/change-password:
    put:
      consumes:
      - application/json
      description: Change password a user
      parameters:
      - description: user ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/change_password.UserInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      security:
      - ApiKeyAuth: []
      summary: Change password a user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
