### Create new User

#URI sugerida: /api/v{n}/users
#Public: Não
#Tipo: POST
#Request: { "name": STRING, "email": STRING, "login": STRING; "password": STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING, “zip_code” : INT } }
#Return Success: { "user" : OBJECT }
#Return Fail: { "error" : "" }

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "",
  "email": "",
  "login": "",
  "password": "",
  "location": {
    "lat": 1.0,
    "lng": 1.0,
    "address": "",
    "city": "",
    "state": "",
    "zip_code": 1
  }
}

> {% client.global.set("user_id", response.body.json.user.id); %}

### Update User
#URI sugerida: /api/v{n}/users/{ID}
#Public: Não
#Tipo: PUT
#Request: { "name": STRING, "email": STRING, "login": STRING; "password": STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING, “zip_code” : INT } }
#Return Success: { "user" : OBJECT }
#Return Fail: { "error" : STRING }

PUT {{host}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "",
  "email": "",
  "login": "",
  "password": "",
  "location": {
    "lat": 1.0,
    "lng": 1.0,
    "address": "",
    "city": "",
    "state": "",
    "zip_code": 1
  }
}

### Find User
#URI sugerida: /api/v{n}/users/{ID}
#Public: NÃO
#Tipo: GET
#Return Success: { "user" : OBJECT }
#Return Fail: { "error" : STRING }

GET {{host}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}


### change password
PUT {{host}}/users/{{user_id}}/change_password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "",
  "new_password": ""
}


