### Create Deal
#URI sugerida: /api/v{n}/deals
#Public: NÃO
#Tipo: POST
#Request: { “type” : ENUM (1 – Venda, 2 – Troca, 3 – Desejo), “value” : DOUBLE, “description” : STRING, “trade_for” : STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING , “zip_code” : INT }, “urgency” : { “type” : ENUM (1 – Baixa, 2 – Média, 3 – Alta, 4 – Data), “limit_date” : DATE}, “photos“ : [ LIST OF IMAGES ]}
#Return Success: { “deal": OBJECT }
#Return Fail: { "error" : STRING }

POST {{host}}/deals
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "ENUM (1 – Venda, 2 – Troca, 3 – Desejo)",
  "value": 1.0,
  "description": "",
  "trade_for": "",
  "location": {
    "lat": 1.0,
    "lng": 1.0,
    "address": "",
    "city": "",
    "state": "",
    "zip_code": 1
  },
  "urgency": {
    "type": "ENUM (1 – Baixa, 2 – Média, 3 – Alta, 4 – Data)",
    "limit_date": "2022-02-23"
  },
  "photos": [
    ""
  ]
}

> {% client.global.set("deal_id", response.body.json.deal.id); %}

### Update Deal
#URI sugerida: /api/v{n}/deals/{ID}
#Public: NÃO
#Tipo: PUT
#Request: { “type” : ENUM (1 – Venda, 2 – Troca, 3 – Desejo), “value” : DOUBLE, “description” : STRING, “trade_for” : STRING, “location” : { “lat” : DOUBLE, “lng” : DOUBLE, “address” : STRING, “city” : STRING, “state”: STRING , “zip_code” : INT }, “urgency” : { “type” : ENUM (1 – Baixa, 2 – Média, 3 – Alta, 4 – Data), “limit_date” : DATE}, “photos“ : [ LIST OF IMAGES ]}
#Return Success: { “deal": OBJECT }
#Return Fail: { "error" : STRING }

PUT {{host}}/deals/{{deal_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "ENUM (1 – Venda, 2 – Troca, 3 – Desejo)",
  "value": 1.0,
  "description": "",
  "trade_for": "",
  "location": {
    "lat": 1.0,
    "lng": 1.0,
    "address": "",
    "city": "",
    "state": "",
    "zip_code": 1
  },
  "urgency": {
    "type": "ENUM (1 – Baixa, 2 – Média, 3 – Alta, 4 – Data)",
    "limit_date": "2022-02-23"
  },
  "photos": [
    ""
  ]
}

### Find Deal
#URI sugerida: /api/v{n}/deals/{ID}
#Public: NÃO
#Tipo: GET
#Return Success: { “deal": OBJECT }
#Return Fail: { "error" : STRING }

GET {{host}}/deals/{{deal_id}}
Authorization: Bearer {{token}}
Content-Type: application/json



